image: Visual Studio 2017
clone_depth: 1
version: '{build}-{branch}'
skip_branch_with_pr: false
configuration: Release

environment:
  matrix:
    - py_version: 35
    - py_version: 36
    - py_version: 37
    - py_version: 38

platform:
  - x86
  - x64

install:
  - set "PYTHON=C:\\Python%py_version%"
  - IF "%PLATFORM%" == "x64" ( set "PYTHON=%PYTHON%-x64" )
  - IF "%PLATFORM%" == "x64" ( set "vcvarsall_arg=amd64" ) ELSE ( set "vcvarsall_arg=x86" )
  - IF "%py_version%" == "34" ( set "DISTUTILS_USE_SDK=1" )
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %vcvarsall_arg%
  - set "PATH=%PYTHON%\\scripts;%PYTHON%;%PATH%"
  - pip install --upgrade setuptools
  - pip install "hypothesis < 5.29"
  - pip install "cython>0.29.20"
  - pip install wheel
  - git config core.symlinks true
  - git reset --hard
  - git submodule init
  - git submodule update
  - pip freeze

build: off

test_script:
  # Run tests (note ci profile takes a while)
  - python setup.py build_ext -i
    #- set HYPOTHESIS_PROFILE=ci
  - python test.py
  - set HYPOTHESIS_PROFILE=dev
  - python -c "import cydoctest, pyroaring; cydoctest.testmod(pyroaring)" -v
  - git clean -xfd
  # Test installation from binary wheel
  - python setup.py bdist_wheel
  - for %%f in (dist\pyroaring*.whl) do (pip install %%~f)
  - python test.py
  - pip uninstall -y pyroaring
  - git clean -xfd
  # Test installation from source distribution
  - python setup.py sdist
  - for %%f in (dist\pyroaring*.tar.gz) do (pip install %%~f)
  - python test.py
  - pip uninstall -y pyroaring
  - git clean -xfd

after_test:
  - python setup.py bdist_wheel
  - python setup.py sdist
  - dir dist

artifacts:
  - path: dist\*.whl
    name: wheel

deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    appveyor_repo_tag: true        # deploy on tag push only
